spring:
  spring:
    h2:
      console:
        enabled: true
        path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 5497
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    secret: "beroberoberoberoberoberoberoberobero"